version: "3.9"
services:
  webdev:
    container_name: budu
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app/
    restart: always
    ports:
      - 3000:3000
